# the fcrepo REST endpoint
REST_ENDPOINT: http://localhost:8080/fcrepo/rest

# credentials to use for your fcrepo
FEDORA_USER: fedoraAdmin
FEDORA_PASSWORD: secret3

ASSET_DIR: "../assets"
METADATA_FILE: "../metadata.csv"
LOG_FILE: "logs/load.log"

# namespaces to pre-bind
NAMESPACE_BINDINGS: 
    audit:          http://fedora.info/definitions/v4/audit#
    authz:          http://fedora.info/definitions/v4/authorization#
    bibo:           http://purl.org/ontology/bibo/
    dc:             http://purl.org/dc/elements/1.1/
    ebucore:        http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#
    ex:             http://www.example.org/terms/
    fedora:         http://fedora.info/definitions/v4/repository#
    fedoraconfig:   http://fedora.info/definitions/v4/config#
    image:          http://www.modeshape.org/images/1.0
    jcr:            http://www.jcp.org/jcr/1.0
    ldp:            http://www.w3.org/ns/ldp#
    mix:            http://www.jcp.org/jcr/mix/1.0
    mode:           http://www.modeshape.org/1.0
    nt:             http://www.jcp.org/jcr/nt/1.0
    pcdm:           http://pcdm.org/models#
    premis:         http://www.loc.gov/premis/rdf/v1#
    prov:           http://www.w3.org/ns/prov#
    sv:             http://www.jcp.org/jcr/sv/1.0
    xml:            http://www.w3.org/XML/1998/namespace
    xmlns:          http://www.w3.org/2000/xmlns/
    xsi:            http://www.w3.org/2001/XMLSchema-instance
