# the fcrepo REST endpoint
REST_ENDPOINT: http://localhost:8080/fcrepo/rest

# credentials to use for your fcrepo
FEDORA_USER: fedoraAdmin
FEDORA_PASSWORD: secret3

# namespaces to pre-bind
NAMESPACE_BINDINGS: 
    bibo: http://purl.org/ontology/bibo/
    dc: http://purl.org/dc/elements/1.1/
    exterms: http://www.example.org/terms/
    foaf: http://xmlns.com/foaf/0.1/
